Internal: add color GraphicalElements4
healthfitnessnordic/SATSCore-iOS pull request #94
Opened 2022-05-11 08:30 UTC by SatseAndrew

# Why?

There is currently an issue in discover where this happens in dark mode.

<img width="392" alt="Screenshot 2022-05-11 at 10 26 05" src="https://user-images.githubusercontent.com/57347029/167804397-7815a8b8-00d3-4d63-b856-666d1ddca828.png">

# What?

Add new color graphicalElements4.

# UI Changes

This is how the icon will look with the new color.

<img width="392" alt="Screenshot 2022-05-11 at 10 29 22" src="https://user-images.githubusercontent.com/57347029/167804904-47495ba6-b4e9-48a9-a8c4-94f300296f52.png">

2022-05-11 10:06 UTC, kentrh requested changes
Test are failing in `ColorTests` because the color hasn't been added there, also a demo of the color is missing in `ColorDemoView`

2022-05-11 12:23 UTC, kentrh commented on DemoApp/DemoApp/Views/DNA/ColorDemoView.swift
> +                ColorDemo(name: "graphicalElements4", color: .graphicalElements3),
```suggestion
                ColorDemo(name: "graphicalElements4", color: .graphicalElements4),
```

2022-05-11 12:33 UTC, fespinoza commented
I added a task for us to take a look at the CI setup 😨

2022-05-16 07:49 UTC, kentrh approved these changes
👍

2022-05-16 07:53 UTC, merged